### ISSUE TITLE
request: skip .gitignore files would be a nice option

### ISSUE THREAD

**Issue by moeriki** [peterdotjs/atom-synced-sidebar#16]
Or any kind option that allows inclusion / exclusion of globs.

For example quite regularly I check the source files of node_modules/\* to see what's going on. I don't need my tree expanding on that. The sidebar quickly becomes a mess this way.

**Comment by simonknittel** [comment]
Would be also be nice to ignore the .git-directory. Everytime when you want to write a commit with git-plus it opens .git-directory and focuses the COMMIT_EDITMSG file
