### ISSUE TITLE
Please remove from https://atom.io/packages/synced-sidebar

### ISSUE THREAD

**Issue by walles** [peterdotjs/atom-synced-sidebar#31]
Since 2015 this functionality is now part of the default TreeView package:
https://github.com/atom/tree-view/commit/5da0a14976dc0626e474324366d3f7e8101facce

Could you please remove this package from <https://atom.io/packages/synced-sidebar>?

Found this while researching https://github.com/walles/atom-shortcuts-teacher/issues/1, and uninstalling synced-sidebar seems like the correct solution for that ticket.

Please let me know if you disagree or if I misunderstood something here.

**Comment by peterdotjs** [comment]
Unpublished from APM.
