### ISSUE TITLE
Editor Pane Loses Focus

### ISSUE THREAD

**Issue by satishmohan** [peterdotjs/atom-synced-sidebar#32]
Hi
Thanks for this great package. However I notice that if I switch tabs using Cmd+1, Cmd+2, etc on Mac OS, the editor pane loses focus and the focus shifts to the sidebar window.

It would be neat if the focus remains on the editor pane.

Thanks
Satish

**Comment by Zeklandia** [comment]
My problem was even worse! On Windows, it would constantly shift the focus back to the sidebar and I couldn't type anything because it would try to make a new file!!

I had to disable this plugin just so I could use Atom.

**Comment by VLstack** [comment]
Same as Zeklandia. Since today (2017-05-17) with version 0.4.3, I have to disable the package in order to be allowed to focus to the editor pane.

**Comment by satishmohan** [comment]
I discovered that this functionality is available in Atom's core tree-view plugin itself - check the Auto Reveal and uncheck the Focus on Reveal options! 

The behavior is correct on this one!

**Comment by peterdotjs** [comment]
@ all apologies this repo hasn't been maintained and Atom itself natively has this feature since it was initially built so I'll move to deprecate it. Thanks for reporting.

**Comment by peterdotjs** [comment]
Unpublished from APM.
