### ISSUE TITLE
Big Bug in ATOM's latest version 

### ISSUE THREAD

**Issue by fenixwu** [peterdotjs/atom-synced-sidebar#33]
Can't type any single word in editor or textfield in Preferences after updating ATOM to 1.17.0 x64.

Disable this plugin and reopen files, Atom works normally.

**Comment by seasick** [comment]
Same here - If I try to write something, it starts various actions.

e.g.
a - opens the "enter path for new file" dialog
d - opens "enter the new path for duplicate."
i - toggles showing .gitignored files

So I guess some kind of modifier is active?

**Comment by acflint** [comment]
Seems like the keyboard remains focused on the project folder sidebar, and won't focus on the text area.

**Comment by VasilStoyanov** [comment]
+1 Experiencing this problem as well.

**Comment by jalendport** [comment]
This is really annoying. Having the same problem.

**Comment by acflint** [comment]
You can remove this package and just use the built in sidebar functionality to achieve the same thing. Here's instructions:
Go to Settings
Packages
Open the tree-view settings
Check the "Auto Reveal" box
Click on an editor tab

**Comment by peterdotjs** [comment]
@ all apologies, this repo hasn't been maintained and Atom itself natively has this feature since it was initially built so I'll move to deprecate it. Thanks for reporting.

**Comment by peterdotjs** [comment]
Unpublished from APM.

**Comment by gbenedict** [comment]
It took me quite a while to track down the issue to this package. You should have probably updated the package and removed the functionality instead of deleting it. Not sure if you can do so now.

**Comment by peterdotjs** [comment]
@gbenedict Hmm you're right that would have been cleaner to assume users would just upgrade to a no-op plugin. I'll try see see if I can republish and update the messaging to disable/uninstall it. Thanks for the feedback - def a good learning experience.

**Comment by mxstbr** [comment]
Had to use a different editor for the past 4 days due to having no idea what broke it, finally tracked it down. I'd definitely prefer having a noop package!

**Comment by kyeongan** [comment]
Same issue. I haven't used 'atom --safe' and finally I am here to read it.

**Comment by WLyKan** [comment]
Thx to @acflint's tip.
Finally I find an unfamous plugin: `https://github.com/smockle/collapse-then-reveal`, and it works good for me.
