### ISSUE TITLE
version 0.4.3 of synced-sidebar is not compatible with atom 0.17.0

### ISSUE THREAD

**Issue by house9** [peterdotjs/atom-synced-sidebar#36]
After upgrading from atom 0.16.0 to 0.17.0 I could no longer type into a file. Trying to type would bring up the duplicate file dialog or add new file dialog, I could not focus on the file itself.

After disabling this package atom usage is normal once again.

**Comment by peterdotjs** [comment]
See https://github.com/peterdotjs/atom-synced-sidebar/issues/33
