### ISSUE TITLE
Deprecated package, atom won't load it

### ISSUE THREAD

**Issue by varemenos** [peterdotjs/atom-synced-sidebar#4]
The package is using deprecated APIs and atom won't load it anymore

**Comment by peterdotjs** [comment]
@varemenos will be resolved at latest by 6/8. I lost access to my Mac and Windows apm push is failing.

**Comment by guyellis** [comment]
Great package/plugin - I just hit this issue as well - appreciate the time you take to maintain this @peterdotjs !!

**Comment by peterdotjs** [comment]
@varemenos @guyellis  Resolved in v0.4. Apologies for the delay!

**Comment by guyellis** [comment]
@peterdotjs Thanks for fixing!

**Comment by varemenos** [comment]
Awesome, thanks a lot
