### ISSUE TITLE
Add option to only sync on demand

### ISSUE THREAD

**Issue by bclinkinbeard** [peterdotjs/atom-synced-sidebar#7]
I don't need/want the sidebar to update every time I switch tabs, but I do miss the ability WebStorm has to sync it on demand. WS has a button at the top of the sidebar that will trigger it, but I think a key command would be sufficient.

**Comment by holyjak** [comment]
Then you don't need the plugin, just use (on Mac) `cmd-shift-\` to sync them

**Comment by bclinkinbeard** [comment]
Aha, thanks!
