### ISSUE TITLE
CMD+1,2,3 Keys Working Erratically

### ISSUE THREAD

**Issue by zenopopovici** [peterdotjs/atom-synced-sidebar#8]
The switching via CMD+numeric keys works erratically with this plugin enabled. I'm guessing that sync doesn't switch back focus from the tree view to the editor once it's done.

**Comment by peterdotjs** [comment]
I'll need to make a change to support this - currently looping through tabs is supported - https://github.com/peterdotjs/atom-synced-sidebar/issues/1

**Comment by niksite** [comment]
If this is fixed in Git, could you please issue new release to atom.io?

**Comment by zenopopovici** [comment]
Maybe look into: https://github.com/peterdotjs/atom-synced-sidebar It seems to have solved all problems.
