### ISSUE TITLE
Changing tab leaves focus on the sidebar (should focus the editor)

### ISSUE THREAD

**Issue by lenart** [peterdotjs/atom-synced-sidebar#9]
When I have more files open and I want to switch between them using `cmd + {` the sidebar always gets focus. It's quite annoying to always have to click the editor or hit `cmd + 1` to return focus to the editor.

```
MAC OSX
Atom 1.0.5
synced-sidebar 0.4.0
```

**Comment by shekibobo** [comment]
:+1:

**Comment by jamal** [comment]
:+1:

**Comment by josegonzalez** [comment]
This should work already, but doesn't. Here was the api deprecation fix: https://github.com/peterdotjs/atom-synced-sidebar/commit/8063f8914c51a9cbe2ce6d4c018d30065a0f22c9

**Comment by NKjoep** [comment]
Hi,
I still have this issue with atom 1.1.0 and synced-sidebar 0.4.2.
I had to disable the the plugin in order to prevent this bug. 

How can I help?

**Comment by peterdotjs** [comment]
@NKjoep if you are interested in helping out feel free to make a pull request!

Issue is here: https://github.com/peterdotjs/atom-synced-sidebar/blob/master/lib/synced-sidebar.coffee#L17

Focus was working at some point in time before 1.0. I haven't really had time to investigate and it doesn't help that I'm starting to to use sublime more and atom less.

**Comment by peterdotjs** [comment]
Thanks @kswedberg for the PR. Fixed in v0.4.3.

**Comment by kswedberg** [comment]
Glad to help. Thank you for the quick turnaround, @peterdotjs !
